// Ballon-hot 气球皮肤数据配置
// 4关 × 10 气球 + 30 传说限定

const BALLOON_TYPES = [
  {
    "id": "candy_round",
    "name": "甜橙圆球",
    "emoji": "🟠",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第1关第1个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#ff9800",
    "glowColor": "#ffb74d",
    "level": 1,
    "shape": "round"
  },
  {
    "id": "candy_heart",
    "name": "蜜糖之心",
    "emoji": "⭐",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第1关第2个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#ffd740",
    "glowColor": "#ffea00",
    "level": 1,
    "shape": "heart"
  },
  {
    "id": "candy_star",
    "name": "糖棒星星",
    "emoji": "🍭",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第1关第3个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#ff80ab",
    "glowColor": "#f06292",
    "level": 1,
    "shape": "star"
  },
  {
    "id": "candy_long",
    "name": "草莓长卷",
    "emoji": "🍓",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第1关第4个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#ff5252",
    "glowColor": "#e53935",
    "level": 1,
    "shape": "long"
  },
  {
    "id": "candy_animal",
    "name": "蜜桃熊宝",
    "emoji": "🍑",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第1关第5个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#ffcc80",
    "glowColor": "#ffab40",
    "level": 1,
    "shape": "animal"
  },
  {
    "id": "candy_cloud",
    "name": "晶糖棉花云",
    "emoji": "🍬",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第1关第6个",
    "unlocked": true,
    "isPaid": false,
    "price": null,
    "color": "#e1bee7",
    "glowColor": "#ba68c8",
    "level": 1,
    "shape": "cloud"
  },
  {
    "id": "candy_diamond",
    "name": "甜甜圈钻",
    "emoji": "🍩",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第1关第7个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffe082",
    "glowColor": "#ffb74d",
    "level": 1,
    "shape": "diamond"
  },
  {
    "id": "candy_twist",
    "name": "樱桃双旋",
    "emoji": "🍒",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第1关第8个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#e53935",
    "glowColor": "#c62828",
    "level": 1,
    "shape": "twist"
  },
  {
    "id": "candy_flower",
    "name": "冰晶糖花",
    "emoji": "🧊",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第1关第9个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#80deea",
    "glowColor": "#26c6da",
    "level": 1,
    "shape": "flower"
  },
  {
    "id": "candy_crown",
    "name": "金菱糖王",
    "emoji": "🔶",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第1关第10个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffb300",
    "glowColor": "#ffd740",
    "level": 1,
    "shape": "crown"
  },
  {
    "id": "neon_round",
    "name": "紫电霓虹球",
    "emoji": "💜",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第2关第1个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#9c27b0",
    "glowColor": "#ce93d8",
    "level": 2,
    "shape": "round"
  },
  {
    "id": "neon_heart",
    "name": "雷霆之心",
    "emoji": "⚡",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第2关第2个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffea00",
    "glowColor": "#ffd740",
    "level": 2,
    "shape": "heart"
  },
  {
    "id": "neon_star",
    "name": "辉光星芒",
    "emoji": "🌟",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第2关第3个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#69ff47",
    "glowColor": "#b2ff59",
    "level": 2,
    "shape": "star"
  },
  {
    "id": "neon_long",
    "name": "魔杖光柱",
    "emoji": "🪄",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第2关第4个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#00e5ff",
    "glowColor": "#18ffff",
    "level": 2,
    "shape": "long"
  },
  {
    "id": "neon_animal",
    "name": "赛博霓虹猫",
    "emoji": "🐱",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第2关第5个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#b388ff",
    "glowColor": "#7c4dff",
    "level": 2,
    "shape": "animal"
  },
  {
    "id": "neon_cloud",
    "name": "数据网络云",
    "emoji": "🌐",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第2关第6个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#18ffff",
    "glowColor": "#00b8d4",
    "level": 2,
    "shape": "cloud"
  },
  {
    "id": "neon_diamond",
    "name": "彩虹光谱钻",
    "emoji": "🌈",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第2关第7个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff6e40",
    "glowColor": "#dd2c00",
    "level": 2,
    "shape": "diamond"
  },
  {
    "id": "neon_twist",
    "name": "电子花旋",
    "emoji": "🌺",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第2关第8个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff4081",
    "glowColor": "#c51162",
    "level": 2,
    "shape": "twist"
  },
  {
    "id": "neon_flower",
    "name": "电音莓花",
    "emoji": "🍓",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第2关第9个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff80ab",
    "glowColor": "#f50057",
    "level": 2,
    "shape": "flower"
  },
  {
    "id": "neon_crown",
    "name": "霓虹金菱冠",
    "emoji": "🔶",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第2关第10个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffd740",
    "glowColor": "#ffab00",
    "level": 2,
    "shape": "crown"
  },
  {
    "id": "lava_round",
    "name": "爆裂火球",
    "emoji": "🧨",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第3关第1个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff3d00",
    "glowColor": "#ff6e40",
    "level": 3,
    "shape": "round"
  },
  {
    "id": "lava_heart",
    "name": "炽热之心",
    "emoji": "❤️‍🔥",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第3关第2个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff1744",
    "glowColor": "#d50000",
    "level": 3,
    "shape": "heart"
  },
  {
    "id": "lava_star",
    "name": "烈焰星火",
    "emoji": "🔥",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第3关第3个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff6d00",
    "glowColor": "#ff9100",
    "level": 3,
    "shape": "star"
  },
  {
    "id": "lava_long",
    "name": "熔铸火刃",
    "emoji": "⚔️",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第3关第4个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#bf360c",
    "glowColor": "#e64a19",
    "level": 3,
    "shape": "long"
  },
  {
    "id": "lava_animal",
    "name": "炎盾熔岩兽",
    "emoji": "🛡️",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第3关第5个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff8a65",
    "glowColor": "#ff5722",
    "level": 3,
    "shape": "animal"
  },
  {
    "id": "lava_cloud",
    "name": "烟尘风暴云",
    "emoji": "💨",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第3关第6个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#bcaaa4",
    "glowColor": "#8d6e63",
    "level": 3,
    "shape": "cloud"
  },
  {
    "id": "lava_diamond",
    "name": "地心火晶钻",
    "emoji": "💠",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第3关第7个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff5252",
    "glowColor": "#d32f2f",
    "level": 3,
    "shape": "diamond"
  },
  {
    "id": "lava_twist",
    "name": "熔岩火漩涡",
    "emoji": "🌀",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第3关第8个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff6d00",
    "glowColor": "#e65100",
    "level": 3,
    "shape": "twist"
  },
  {
    "id": "lava_flower",
    "name": "烈焰魔花",
    "emoji": "🎃",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第3关第9个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ff9100",
    "glowColor": "#e65100",
    "level": 3,
    "shape": "flower"
  },
  {
    "id": "lava_crown",
    "name": "熔炉金菱冠",
    "emoji": "🔶",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第3关第10个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffab00",
    "glowColor": "#ff6d00",
    "level": 3,
    "shape": "crown"
  },
  {
    "id": "temple_round",
    "name": "月华圆球",
    "emoji": "🌙",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第4关第1个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#b3e5fc",
    "glowColor": "#e1f5fe",
    "level": 4,
    "shape": "round"
  },
  {
    "id": "temple_heart",
    "name": "纯白之心",
    "emoji": "🤍",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第4关第2个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#f5f5f5",
    "glowColor": "#e0e0e0",
    "level": 4,
    "shape": "heart"
  },
  {
    "id": "temple_star",
    "name": "天界星光",
    "emoji": "🚀",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第4关第3个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#fff9c4",
    "glowColor": "#fff176",
    "level": 4,
    "shape": "star"
  },
  {
    "id": "temple_long",
    "name": "圣爱心柱",
    "emoji": "💖",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第4关第4个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#f8bbd0",
    "glowColor": "#f48fb1",
    "level": 4,
    "shape": "long"
  },
  {
    "id": "temple_animal",
    "name": "祥云神兽",
    "emoji": "⛅",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第4关第5个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#e0f7fa",
    "glowColor": "#80deea",
    "level": 4,
    "shape": "animal"
  },
  {
    "id": "temple_cloud",
    "name": "预言晶云",
    "emoji": "🔮",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第4关第6个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ce93d8",
    "glowColor": "#ab47bc",
    "level": 4,
    "shape": "cloud"
  },
  {
    "id": "temple_diamond",
    "name": "天界风钻",
    "emoji": "🌪️",
    "rarity": "稀有",
    "rarityColor": "#4fc3f7",
    "unlockCondition": "第4关第7个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#b3e5fc",
    "glowColor": "#4fc3f7",
    "level": 4,
    "shape": "diamond"
  },
  {
    "id": "temple_twist",
    "name": "圣莲双旋",
    "emoji": "🪷",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第4关第8个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#f8bbd0",
    "glowColor": "#f06292",
    "level": 4,
    "shape": "twist"
  },
  {
    "id": "temple_flower",
    "name": "晴空祥云花",
    "emoji": "🌤️",
    "rarity": "史诗",
    "rarityColor": "#ce93d8",
    "unlockCondition": "第4关第9个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#fff3e0",
    "glowColor": "#ffe0b2",
    "level": 4,
    "shape": "flower"
  },
  {
    "id": "temple_crown",
    "name": "神殿金菱冠",
    "emoji": "🔶",
    "rarity": "普通",
    "rarityColor": "#aaaaaa",
    "unlockCondition": "第4关第10个",
    "unlocked": false,
    "isPaid": false,
    "price": null,
    "color": "#ffe082",
    "glowColor": "#ffd54f",
    "level": 4,
    "shape": "crown"
  },
  {
    "id": "legend_imperial_crown",
    "name": "至尊皇冠",
    "emoji": "👑",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffd700",
    "glowColor": "#ffab00",
    "level": 0,
    "shape": "crown"
  },
  {
    "id": "legend_dream_bubble",
    "name": "幻梦气泡",
    "emoji": "🫧",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#e0f7fa",
    "glowColor": "#b2ebf2",
    "level": 0,
    "shape": "round"
  },
  {
    "id": "legend_star_radiance",
    "name": "星光璀璨",
    "emoji": "✨",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffd740",
    "glowColor": "#ffea00",
    "level": 0,
    "shape": "star"
  },
  {
    "id": "legend_gold_trophy",
    "name": "黄金奖杯",
    "emoji": "🏆",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffb300",
    "glowColor": "#ffd740",
    "level": 0,
    "shape": "crown"
  },
  {
    "id": "legend_unicorn",
    "name": "独角神兽",
    "emoji": "🦄",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#e1bee7",
    "glowColor": "#ce93d8",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_lion_king",
    "name": "雄狮之王",
    "emoji": "🦁",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffb74d",
    "glowColor": "#ff9800",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_sky_eagle",
    "name": "苍穹猎鹰",
    "emoji": "🦅",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#90caf9",
    "glowColor": "#42a5f5",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_night_wolf",
    "name": "暗夜狼王",
    "emoji": "🐺",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#78909c",
    "glowColor": "#546e7a",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_abyss_croc",
    "name": "深渊鳄王",
    "emoji": "🐊",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#66bb6a",
    "glowColor": "#43a047",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_peacock_king",
    "name": "孔雀明王",
    "emoji": "🦚",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#4dd0e1",
    "glowColor": "#00bcd4",
    "level": 0,
    "shape": "flower"
  },
  {
    "id": "legend_fate_crystal",
    "name": "命运水晶",
    "emoji": "🔮",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ce93d8",
    "glowColor": "#ab47bc",
    "level": 0,
    "shape": "diamond"
  },
  {
    "id": "legend_shooting_star1",
    "name": "流星幻影",
    "emoji": "💫",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#fff176",
    "glowColor": "#ffd740",
    "level": 0,
    "shape": "star"
  },
  {
    "id": "legend_heart_gift",
    "name": "心动之礼",
    "emoji": "💝",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ff4081",
    "glowColor": "#f50057",
    "level": 0,
    "shape": "heart"
  },
  {
    "id": "legend_wind_chime",
    "name": "风铃清音",
    "emoji": "🎐",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#b3e5fc",
    "glowColor": "#81d4fa",
    "level": 0,
    "shape": "cloud"
  },
  {
    "id": "legend_saturn_ring",
    "name": "土星环冕",
    "emoji": "🪐",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffe0b2",
    "glowColor": "#ffcc80",
    "level": 0,
    "shape": "round"
  },
  {
    "id": "legend_frost_crystal",
    "name": "冰霜雪晶",
    "emoji": "❄️",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#e3f2fd",
    "glowColor": "#bbdefb",
    "level": 0,
    "shape": "diamond"
  },
  {
    "id": "legend_rainbow_bridge",
    "name": "彩虹天桥",
    "emoji": "🌈",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#66bb6a",
    "glowColor": "#ff6e40",
    "level": 0,
    "shape": "twist"
  },
  {
    "id": "legend_azure_heart",
    "name": "碧蓝心海",
    "emoji": "🩵",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#4fc3f7",
    "glowColor": "#03a9f4",
    "level": 0,
    "shape": "heart"
  },
  {
    "id": "legend_guardian_eye",
    "name": "守护之瞳",
    "emoji": "🧿",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#1e88e5",
    "glowColor": "#1565c0",
    "level": 0,
    "shape": "round"
  },
  {
    "id": "legend_tiger_roar",
    "name": "虎啸苍穹",
    "emoji": "🐯",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ff9800",
    "glowColor": "#e65100",
    "level": 0,
    "shape": "animal"
  },
  {
    "id": "legend_galaxy_spin",
    "name": "星河旋转",
    "emoji": "💫",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#7c4dff",
    "glowColor": "#b388ff",
    "level": 0,
    "shape": "twist"
  },
  {
    "id": "legend_eternal_diamond",
    "name": "永恒钻石",
    "emoji": "💎",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#80d8ff",
    "glowColor": "#40c4ff",
    "level": 0,
    "shape": "diamond"
  },
  {
    "id": "legend_divine_fleur",
    "name": "圣光鸢尾",
    "emoji": "⚜️",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#fff9c4",
    "glowColor": "#fff176",
    "level": 0,
    "shape": "flower"
  },
  {
    "id": "legend_secret_key",
    "name": "秘境之钥",
    "emoji": "🗝️",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffe082",
    "glowColor": "#ffb300",
    "level": 0,
    "shape": "long"
  },
  {
    "id": "legend_poseidon_trident",
    "name": "海神三叉戟",
    "emoji": "🔱",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#40c4ff",
    "glowColor": "#0288d1",
    "level": 0,
    "shape": "long"
  },
  {
    "id": "legend_wishing_star",
    "name": "许愿流星",
    "emoji": "🌠",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#fff176",
    "glowColor": "#ffab00",
    "level": 0,
    "shape": "star"
  },
  {
    "id": "legend_crystal_butterfly",
    "name": "晶蝶飞舞",
    "emoji": "🦋",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#bbdefb",
    "glowColor": "#64b5f6",
    "level": 0,
    "shape": "cloud"
  },
  {
    "id": "legend_theater_mask",
    "name": "幻变面具",
    "emoji": "🎭",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ce93d8",
    "glowColor": "#8e24aa",
    "level": 0,
    "shape": "heart"
  },
  {
    "id": "legend_gleaming_gem",
    "name": "流光宝石",
    "emoji": "💠",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#80cbc4",
    "glowColor": "#26a69a",
    "level": 0,
    "shape": "diamond"
  },
  {
    "id": "legend_gold_medal",
    "name": "至尊金牌",
    "emoji": "🥇",
    "rarity": "传说",
    "rarityColor": "#ffd700",
    "unlockCondition": "限定付费解锁",
    "unlocked": false,
    "isPaid": true,
    "price": "¥6",
    "color": "#ffd740",
    "glowColor": "#ff9100",
    "level": 0,
    "shape": "crown"
  }
];

const LEVELS = [
  { id: 1, name: "糖果乐园", targetMin: 70, targetMax: 85, background: "candy", description: "甜蜜的开始", difficulty: 1, zoneWidth: 15, emojiSeq: "candy" },
  { id: 2, name: "霓虹街道", targetMin: 78, targetMax: 88, background: "neon", description: "城市的夜晚", difficulty: 2, zoneWidth: 10, emojiSeq: "neon" },
  { id: 3, name: "暗红熔炉", targetMin: 80, targetMax: 87, background: "lava", description: "极限高温挑战", difficulty: 3, zoneWidth: 7, emojiSeq: "lava" },
  { id: 4, name: "云端神殿", targetMin: 83, targetMax: 86, background: "temple", description: "隐藏指针，感受气息", difficulty: 4, zoneWidth: 3, emojiSeq: "temple" }
];

const TEAM_MEMBERS = [
  { rank: 1, avatar: "", avatarColor: "#ff6eb4", name: "糖果小仙女", score: 2840, isLeader: true },
  { rank: 2, avatar: "", avatarColor: "#40c4ff", name: "霓虹战士", score: 2310 },
  { rank: 3, avatar: "", avatarColor: "#b388ff", name: "星河漫游者", score: 1980 },
  { rank: 4, avatar: "", avatarColor: "#ff6d00", name: "烈焰骑士", score: 1750 },
  { rank: 5, avatar: "", avatarColor: "#69ff47", name: "薄荷冰淇淋", score: 1620 }
];

module.exports = { BALLOON_TYPES, LEVELS, TEAM_MEMBERS };
